server:
  port: 8080

spring:
  port: 8080
  datasource:
    #url: jdbc:mysql://47.107.226.8:3306/test?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    #password: 123456
    password: Abc123!_
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.donglei.blog.entity

img:
  #location: C:/Users/18451/Desktop/upload
  location: /usr/developer/apache-tomcat-8.5.37/webapps/ROOT/images

